version: '3.8'

services:
  training:
    build: .
    command: "training/train.py"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./configs:/app/configs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  inference:
    build: .
    command: "inference/inference.py"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./configs:/app/configs
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
